name: Push into Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        ENV: PROD
      with:
        name: ghcr.io/tscheuneman/go-search/client
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ghcr.io
        context: ${{ github.workspace }}
        dockerfile: ${{ github.workspace }}/deploy/Dockerfile
