name: Push into Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: VaultVulp/gp-docker-action@1.2.0
      env:
        ENV: PROD
      with:
        image-name: go-search/client
        github-token: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ${{ github.workspace }}/Provisioning/go.prod.dockerfile